### ISSUE TITLE
2049897956.json is missing in the German Localized .zip

### ISSUE THREAD

**Issue by LiquidzDEV** [Micky5991/GT-MP-vehicleInfo#1]
![image](https://user-images.githubusercontent.com/20011008/31635420-ee35ecd2-b2c6-11e7-8cf0-179fdd99158d.png)

**Comment by Micky5991** [comment]
Did you download the right pack? That vehicle is a smuggler's run vehicle and not included in the top release. You have to download the smuggler's run pack for it.

https://github.com/Micky5991/GT-MP-vehicleInfo/releases/tag/V1.4.0-sr
