### ISSUE TITLE
Brazilian Portuguese translation for vehicleInfo.json

### ISSUE THREAD

**Issue by oaojmiguel** [Micky5991/GT-MP-vehicleInfo#3]
Hello!

I would like to know if you can provide 'pt-br' (Brazilian Portuguese) translation of vehicleInfo-en.full.json

Thank you for your awesome work.

**Comment by Micky5991** [comment]
Sure, here you go. You can find the files in the [latest release](https://github.com/Micky5991/GT-MP-vehicleInfo/releases/tag/V1.4.1-aw).

https://github.com/Micky5991/GT-MP-vehicleInfo/releases/download/V1.4.1-aw/vehicleInfo-pt-br.full.json
https://github.com/Micky5991/GT-MP-vehicleInfo/releases/download/V1.4.1-aw/vehicleInfo-pt-br.zip
